### PR TITLE
Checkbox fix

### PR DESCRIPTION
**Pull request by Dr-Yukon**
http://screenshot.ru/2076f9951f7ae3481bd2f3710cce5d7a.png "Minor changes" checkbox is not an "Edit summary"

http://screenshot.ru/2100551643a94e631e6986ef402a8ea4.png vertical align of the "Edit summary" label is fixed

### CODE REVIEW

**Comment by dwp-forge** [comment]
I don't see this problem on default template because of `vertical-align: top` rule for `td` elements. I guess, you are using some different template, which does not define such rule. I would prefer adding an explicit alignment rule to `#batchedit td`, rather then fixing alignment with HTML hack.

**Comment by dwp-forge** [comment]
Also on your screenshots all edit fields are lumped together, which doesn't look good. Which template do you use?

**Comment by Dr-Yukon** [comment]
> Also on your screenshots, all edit fields are lumped together, which doesn't look good. Which template do you use?

Selfmade

**Comment by Dr-Yukon** [comment]
Ok, add vertical-align: top to your tables, I close this fix

**Pull request closed without merging**
